name: Deploy to GitHub Pages

on:
  push:
    branches:
      - new-version-website  # Surveille les pushs sur la branche de déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ajuste selon la version Node.js de ton projet

    # 3. Installer les dépendances
    - name: Install dependencies
      run: npm install

    # 4. Build le projet
    - name: Build project
      run: npm run build

    # 5. Nettoyer le dossier /docs et déplacer le build dedans
    - name: Copy build to docs folder
      run: |
        rm -rf docs/*
        mv dist/* docs/
        cp CNAME docs/  # Ajoute cette ligne pour copier le fichier CNAME

    # 6. Commit et push les modifications dans /docs
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/
        git commit -m "Deploy updated site with custom domain" || echo "No changes to commit"
        git push
