name: Deploy to GitHub Pages

on:
  push:
    branches:
      - new-version-website  # Branche à surveiller pour le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Remplace par la version Node.js utilisée dans ton projet

    # 3. Installer les dépendances
    - name: Install dependencies
      run: npm install

    # 4. Build le projet
    - name: Build project
      run: npm run build

    # 5. Nettoyer le dossier docs/ et déplacer le build
    - name: Clean docs/ and move build
      run: |
        rm -rf docs/*
        mv dist/* docs/

    # 6. Commit et push des changements dans la branche `new-version-website`
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "Deploy to GitHub Pages via GitHub Actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
