name: Deploy to GitHub Pages

on:
  push:
    branches:
      - new-version-website  # Surveille les pushs sur la branche de déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ajuste selon la version Node.js de ton projet

    # 3. Installer les dépendances
    - name: Install dependencies
      run: npm install

    # 4. Build le projet
    - name: Build project
      run: npm run build

    # 5. Déployer dans GitHub Pages à partir de ./dist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Répertoire généré par le build
